### ISSUE TITLE
Weird, just started having this issue

### ISSUE THREAD

**Issue by kenpoh01** [vilemduha/blendercam#115]
Just opened Blender CAM and all of a sudden, I'm getting errors and it won't simulate.  It was working fine the other day...
![magic_003](https://user-images.githubusercontent.com/36082436/51068091-39a11f00-15e7-11e9-99de-8a9f1d475d6b.jpg)

**Comment by ksuprynowicz** [comment]
I've just checked it and simulation seems to work fine for me. Can you post the .blend file here?

That having said, I strongly suggest using [CAMotics](https://www.camotics.org/) for final check - you can playback machine motion in real time and check for undercuts (it works on voxel instead of heightmap).
