### ISSUE TITLE
Problems without "auto subdivide long edges"

### ISSUE THREAD

**Issue by jmpocheau** [vilemduha/blendercam#134]
Hi, 
I found a strange issue with BlenderCam in Blender 2.80.
Sometimes the tool paths include additional "holes" which seem to be random.
I tried to analyse this and ended with a very simple example : a cube.

When I use a simple 0.2m cube as model, it works well (First screenshot).
But, when I rotate it 10°, the tool path shows strange holes inside the cube (second screenshot).
When I switch on the auto subdivide long edges parameter, everything goes right (third screenshot).

Is there any point not to keep this parameter always on ?

Thanks in advance,
Jean-Marc
![TestCube1ToolPath](https://user-images.githubusercontent.com/46762963/70706991-6702bb00-1cd7-11ea-961d-f664bbdf1750.png)
![TestCube4ToolPath](https://user-images.githubusercontent.com/46762963/70707013-75e96d80-1cd7-11ea-8df5-bc0fb9291911.png)
![TestCube2ToolPath](https://user-images.githubusercontent.com/46762963/70707075-9dd8d100-1cd7-11ea-82ed-796722b8cb38.png)

**Comment by TurBoss** [comment]
hello!

nice find this bug has been messing arround for a while
I'll try to find what makes it fix the random z moves

**Comment by ksuprynowicz** [comment]
Hi!
The problem with random z plunges is caused by collision detection library which is built into Blender.
Currently there are two ways to fix it - one is, as you said, selecting auto subdivide long edges option (be careful, it may still happen sometimes so still run simulation before machining).
The second way is using OpenCAMLib for collision detection:
https://github.com/vilemduha/blendercam/wiki/Using-BlenderCAM-with-OpenCAMLib
OpenCAMLib is very fast (up to 50 times faster on 24-core machine) and always gives accurate results.

>  Is there any point not to keep this parameter always on ?

The reason that "auto subdivide long edges" is not always set is that it would cause problems like increased memory usage for very complex models (like 10+ million polygons), but I think that automatically switching it on when using collision detection integrated in Blender would be a good idea (correct results are more important than performance), as long as it is always off when using OpenCAMLib.

**Comment by jmpocheau** [comment]
Thanks a lot for those explanations.
I will try to give OpenCAMLib a new chance ... I installed it but only got error message.
I'll review my installation and let you know if I find any problem.
Thanks again
