### ISSUE TITLE
calculate path for groups

### ISSUE THREAD

**Issue by TurBoss** [vilemduha/blendercam#136]
there is some un ported code that still uses groups and not collections

tried to fix but can't figure out

**Comment by Franckapik** [comment]
It seem's that we have the same when we try to use drill strategy ... 

![image](https://user-images.githubusercontent.com/21478769/71063492-12df5700-216d-11ea-9764-ad40e8cc50a4.png)

**Comment by ksuprynowicz** [comment]
I'll have a look at it soon, collection as an operation source would be useful and drill is a must have.

**Comment by Franckapik** [comment]
Is there a way we can help on this ? Is this just a kind of replacement of words or we have to rewrite totally the code ?

**Comment by ksuprynowicz** [comment]
Thank you for reminding me about this. Luckily it turned out to be mostly word replacements, with one rather interesting bug - endless duplication of objects :)
I've tested it on collections of meshes and collections of curves and it seems to work. I still have to test it with OpenCAMLib.
Let me know if it works for you.

**Comment by ksuprynowicz** [comment]
Drill strategy also seems to work again as intended.

**Comment by TurBoss** [comment]
I'm just testing it
amazing work 
thank you so much

**Comment by Franckapik** [comment]
It works !
Thank you so much for having spending time for this !! 
BlenderCam is a excellent tool now !

**Comment by ksuprynowicz** [comment]
You're welcome! :)
